In [1]:
import numpy as np

Завдання 1

Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5% годовых, по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам сумму в 2250 у.е. с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц он положил на каждый счет изначально?

0.05*x1 + 0.07*x2 + 0*x3 = 2250;

0*x1 + 0.07*x2 + 0.06*x3 = 1400;

x1 + x2 + x3 = 5000;

In [12]:
A = np.matrix([[0.05 , 0.07, 0], [0, 0.07, 0.06], [1, 1, 1]])
B = np.matrix([[2250], [1400], [50000]])
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)

[[28617.0212766 ]
 [11702.12765957]
 [ 9680.85106383]]


Завдання 2.

На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра. Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12. Сколько моделей каждого вида на складе?

x1 + x2 + x3 = 1328

x1 - x2 + 0*x3 = -120

x1 + 0*x2 - x3 = 100

In [15]:
A = np.matrix('1,1,1; 1, -1, 0; 1, 0, -1')
B = np.matrix('1328; -120; 100')
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)

[[436.]
 [556.]
 [336.]]


Завдання 3.

Составьте каноническое уравнение эллипсоида, проходящего через три точки A,B,C

A(sqrt(3);0;sqrt(3)), B(sqrt(6); 1/2; 0), C(1; 1/sqrt(3); 1)

Каноническое уравнение эллипсоида в прямоугольной декартовой системе координат имеет вид:

x**2/a**2 + y**2/b**2 + z**2/c**2 = 1

Задача состоит в определении параметров a^2, b^2 и c^2.

x1 = 1/a^2

x2 = 1/b^2

x3 = 1/c^2

Система рівняннь набуває виду:

3*x1 + 0*x2 + 3*x3 = 1

6*x1 + 1/4*x2 + 0*x3 = 1

1*x1 + 1/3*x2 + 1*x3 = 1

In [22]:
A = np.matrix([[3,0,3], [6, 0.25, 0], [1, 1/3, 1]])
B = np.matrix('1; 1; 1')
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)
res = np.matrix([[(1 / X[0,0])], [(1 / X[1,0])], [(1 / X[2,0])]])
print('\n')
print(res)

[[0.08333333]
 [2.        ]
 [0.25      ]]


[[12. ]
 [ 0.5]
 [ 4. ]]


Завдання 4.

Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2). Необходимо найти коэффициенты уравнения a,b,c

y = a*x**2 + b*x +c

x1*1 + x2*1 + x3 = 12

x1*(3*3) + x2*3 + x3 = 54

x1*1 - x2 + x3 = 2

In [3]:
A = np.matrix('1, 1, 1; 9, 3, 1; 1, -1, 1')
B = np.matrix('12; 54; 2')
A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print(X)

[[4.]
 [5.]
 [3.]]


Завдання 5.

Составьте функцию get_polynom, которая по набору точек вида (x1,y1),(x2,y2), ..., (x{n+1}, y{n+1}) будет находить коэффициенты многочлена ci. Таким образом функция принимает список кортежей с координатами и возвращает набор коэффициентов c0,c1, ... ,cn
​


In [17]:
import numpy as np


def get_polynom(coords, n = 4):
    a_list = []
    b_list = []
    for i in coords:
      temp_list = []

      count = n
      for j in range(count):
          temp_list.append(i[0] ** (count-1))
          count -= 1
          #print(count)
      
      a_list.append(temp_list)
      b_list.append(i[1])
      
    a = np.matrix(a_list)
    b = np.array(b_list)
    print(a)
    print(b)
    return np.linalg.solve(a, b)

coords = ((1,0), (3,2), (4,3), (7,1))
print(get_polynom(coords))

[[  1   1   1   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [343  49   7   1]]
[0 2 3 1]
[-0.06944444  0.55555556 -0.31944444 -0.16666667]
