In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression, RidgeClassifier, LinearRegression
from sklearn.metrics import  mean_absolute_error, mean_squared_error, r2_score
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, precision_score, recall_score
from sklearn.datasets import load_wine

# Задание 1

1.   Загрузите "винный" датасет.

2.   Изучите документацию функции train_test_split. С ее помощью датасет можно разделить на тренировочную и тестовую выборки. Первая нужна для обучения модели, а вторая - для оценки качества модели.

3. Разделите wine_dataset на обучающую и тестовую выборки.

4. Обучите модель на тренировочной выборке и оцените ее качество на тестовой.

5. Попробуйте повторить шаги 3 и 4 разбив датасет на обучающую и тестовую выборки в какой-то собственной пропорции. Как это отразилось на качестве модели?

In [8]:
wine_dataset = load_wine()

In [9]:
X = pd.DataFrame(data = wine_dataset.data, columns = wine_dataset.feature_names)
X.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [40]:
y = pd.Series(wine_dataset.target)
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [24]:
print(f'f1_score {f1_score(y_test,y_pred, average = "macro")}')

print(f'accuracy_score {accuracy_score(y_test,y_pred)}')

print(f'precision_score {precision_score(y_test,y_pred, average = "macro")}')

print(f'recall_score {recall_score(y_test,y_pred, average = "macro")}')

print(f'confusion_matrix \n {confusion_matrix(y_test,y_pred)}')

f1_score 1.0
accuracy_score 1.0
precision_score 1.0
recall_score 1.0
confusion_matrix 
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [28]:
print(f'f1_score {f1_score(y_test,y_pred, average = "macro")}')

print(f'accuracy_score {accuracy_score(y_test,y_pred)}')

print(f'precision_score {precision_score(y_test,y_pred, average = "macro")}')

print(f'recall_score {recall_score(y_test,y_pred, average = "macro")}')

print(f'confusion_matrix \n {confusion_matrix(y_test,y_pred)}')

f1_score 0.9859885105786744
accuracy_score 0.9861111111111112
precision_score 0.9833333333333334
recall_score 0.989247311827957
confusion_matrix 
 [[22  0  0]
 [ 0 30  1]
 [ 0  0 19]]


In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [30]:
print(f'f1_score {f1_score(y_test,y_pred, average = "macro")}')

print(f'accuracy_score {accuracy_score(y_test,y_pred)}')

print(f'precision_score {precision_score(y_test,y_pred, average = "macro")}')

print(f'recall_score {recall_score(y_test,y_pred, average = "macro")}')

print(f'confusion_matrix \n {confusion_matrix(y_test,y_pred)}')

f1_score 0.9781143226521377
accuracy_score 0.9775280898876404
precision_score 0.9738461538461539
recall_score 0.9833333333333334
confusion_matrix 
 [[25  0  0]
 [ 1 38  1]
 [ 0  0 24]]


**Вывод:** С уменьшением тестовых данных, качество модели ухудшается!

# Задание 2

Постройте линейный классификатор подобно тому, как мы это делали в задании 1 на датасете Ириса Фишера. Оформите решение в виде jupyter ноутбука.

In [31]:
from sklearn.datasets import load_iris

In [35]:
iris_dataset = load_iris(as_frame=True)

In [50]:
X = iris_dataset.data
X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [48]:
y = iris_dataset.target
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [53]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
model = RidgeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [55]:
print(f'f1_score {f1_score(y_test,y_pred, average = "macro")}')

print(f'accuracy_score {accuracy_score(y_test,y_pred)}')

print(f'precision_score {precision_score(y_test,y_pred, average = "macro")}')

print(f'recall_score {recall_score(y_test,y_pred, average = "macro")}')

print(f'confusion_matrix \n {confusion_matrix(y_test,y_pred)}')

f1_score 0.7840909090909092
accuracy_score 0.8
precision_score 0.7962962962962963
recall_score 0.8162393162393163
confusion_matrix 
 [[11  0  0]
 [ 0  8  5]
 [ 0  1  5]]


# Задание 3

В этом задании нам предстоит построить линейный регрессор. В этот раз мы будем работать с данными о заболевании диабетом. Аналогично заданию 1 выполните следующие шаги:

1. Загрузите датасет.

2. Разделите его на тренировочную и тестовую выборки.

3. На тренировочной выборке обучите линейную модель.

4. Оцените ее качество на тестовой выборке.

5. Попробуйте повторить шаги 1-4 разбив датасет на обучающую и тестовую выборки в какой-то собственной пропорции. Как это отразилось на качестве модели?

In [92]:
from sklearn.datasets import load_diabetes

In [93]:
diabetes_dataset = load_diabetes(as_frame=True)

In [94]:
X = diabetes_dataset.data
X.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [95]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB


In [96]:
y = diabetes_dataset.target
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: target, dtype: float64

In [80]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [133]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

model_score 0.5302453389460016
mean_absolute_error 43.78042313573479
mean_squared_error 3111.992562407689
r2_score 0.3572057694254954


In [134]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

model_score 0.5539285357415583
mean_absolute_error 46.1742024187542
mean_squared_error 3424.316688213733
r2_score 0.33222203269065176


In [135]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

model_score 0.5539411781927148
mean_absolute_error 44.61794011407202
mean_squared_error 3097.1461383877977
r2_score 0.3928939845074757


In [136]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

model_score 0.5791093300283947
mean_absolute_error 45.556752265853916
mean_squared_error 3233.1544248914875
r2_score 0.3865416394270984


In [137]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

model_score 0.5730746555685651
mean_absolute_error 44.80075229864244
mean_squared_error 3075.3333480449564
r2_score 0.4377492256245158


In [138]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.6, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

model_score 0.59809485466992
mean_absolute_error 45.97919822200998
mean_squared_error 3250.304648614086
r2_score 0.42249561422405923


In [125]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.7, random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f'model_score {model.score(X_train, y_train)}')

print(f'mean_absolute_error {mean_absolute_error(y_test,y_pred)}')

print(f'mean_squared_error {mean_squared_error(y_test,y_pred)}')

print(f'r2_score {r2_score(y_test,y_pred)}')

mean_absolute_error 45.28532171529825
mean_squared_error 3131.1123712758454
r2_score 0.4429207846741485


Лучше всего модель показала себя при test_size=0.5.

In [119]:
from sklearn.ensemble import RandomForestRegressor

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
model = RandomForestRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
r2_score(y_test,y_pred)

0.3063488045118935